- name: Create a node, pool and VIP and take the node out of circulation
  hosts: "{{ hosts }}"
  connection: local

  tasks:
      - name: Get all of the facts from my BIG-IP
        bigip_facts:
            server: "{{ inventory_hostname }}"
            user: "{{username}}"
            password: "{{password}}"
            include: "system_info,software,self_ip"
            validate_certs: "false"

      - name: Mention the Self IP
        debug:
            msg: "I have self IP {{ self_ip['/Common/10.0.1.10'].address }}"

      - name: Mention the software
        debug:
            msg: "I have software version {{ software[0].version }}"

      - name: Add a new node blue01
        bigip_node:
            server: "{{ inventory_hostname }}"
            user: "{{username}}"
            password: "{{password}}"
            host: "10.0.2.101"
            name: "blue01"
            validate_certs: "false"
            state: "present"
            monitors:
              - /Common/icmp

      - name: Add a new node blue02
        bigip_node:
            server: "{{ inventory_hostname }}"
            user: "{{username}}"
            password: "{{password}}"
            host: "10.0.2.102"
            name: "blue02"
            validate_certs: "false"
            state: "present"
            monitors:
              - /Common/icmp

      - name: Add a new node green01
        bigip_node:
            server: "{{ inventory_hostname }}"
            user: "{{username}}"
            password: "{{password}}"
            host: "10.0.2.111"
            name: "green01"
            validate_certs: "false"
            state: "present"
            monitors:
              - /Common/icmp

      - name: Add a new node green02
        bigip_node:
            server: "{{ inventory_hostname }}"
            user: "{{username}}"
            password: "{{password}}"
            host: "10.0.2.112"
            name: "green02"
            validate_certs: "false"
            state: "present"
            monitors:
              - /Common/icmp

      - name: Create the blue_green_pool pool
        bigip_pool:
            server: "{{ inventory_hostname }}"
            user: "{{username}}"
            password: "{{password}}"
            name: "blue_green_pool"
            validate_certs: "false"
            monitors:
              - /Common/http

      - name: Add members into blue_green_pool
        bigip_pool_member:
            server: "{{ inventory_hostname }}"
            user: "{{username}}"
            password: "{{password}}"
            state: "present"
            host: "{{ item }}"
            pool: "blue_green_pool"
            port: "80"
            validate_certs: "false"
        with_items:
            - blue01
            - blue02
            - green01
            - green02

      - name: Add the iRule contained in the static file irule-sorry.tcl to the LTM module
        bigip_irule:
            module: "ltm"
            server: "{{ inventory_hostname }}"
            user: "{{username}}"
            password: "{{password}}"
            name: "Sorry_iRule"
            src: "irule-sorry.tcl"
            validate_certs: "no"

      - name: Create a VIP
        bigip_virtual_server:
            server: "{{ inventory_hostname }}"
            description: "blue green VIP"
            destination: "10.0.2.183"
            user: "{{username}}"
            password: "{{password}}"
            name: "blue_green_vip"
            pool: "blue_green_pool"
            port: "8080"
            snat: "Automap"
            all_profiles:
                - "http"
            all_rules:
                - "Sorry_iRule"
            validate_certs: "no"

      - name: Drop members out of gw_pool
        bigip_pool_member:
            server: "{{ inventory_hostname }}"
            user: "{{username}}"
            password: "{{password}}"
            state: "present"
            session_state: "disabled"
            host: "{{ item }}"
            pool: "blue_green_pool"
            port: "80"
            validate_certs: "false"
        with_items:
            - blue01
            - blue02
